# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

require 'google/protobuf'


descriptor_data = "\n\raccount.proto\x12\x10xray.proxy.vless\"7\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66low\x18\x02 \x01(\t\x12\x12\n\nencryption\x18\x03 \x01(\tBR\n\x14\x63om.xray.proxy.vlessP\x01Z%github.com/xtls/xray-core/proxy/vless\xaa\x02\x10Xray.Proxy.Vlessb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Xray
  module Proxy
    module Vless
      Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.proxy.vless.Account").msgclass
    end
  end
end
