# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transport/internet/xhttp/config.proto

require 'google/protobuf'


descriptor_data = "\n%transport/internet/xhttp/config.proto\x12\x1dxray.transport.internet.xhttp\"2\n\x06\x43onfig\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\tB\x84\x01\n!com.xray.transport.internet.xhttpB\x0b\x43onfigProtoZ2github.com/xtls/xray-core/transport/internet/xhttp\xaa\x02\x1dXray.Transport.Internet.Xhttpb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Xray
  module Transport
    module Internet
      module Xhttp
        Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("xray.transport.internet.xhttp.Config").msgclass
      end
    end
  end
end
